services:
  db:
    image: postgres
    container_name: vms-manager-db
    restart: always
    shm_size: 128mb
    networks:
      - manager-db
    env_file:
      - .env
    volumes:
      - /dbstorage/vms-manager-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  vms-manager:
    build: .
    container_name: vms-manager
    env_file:
      - .env
    networks:
      - webserver-manager
      - manager-db
    depends_on:
      db:
        condition: service_healthy
    restart: always

networks:
  webserver-manager:
    name: webserver-manager
  manager-db:
    name: manager-db
